{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
{{- if .Values.gcsgateway.enabled }}
  {{- if .Values.gcsgateway.encodedJson }}
  gcs_key.json: {{ .Values.gcsgateway.encodedJson }}
  {{- else if .Values.gcsgateway.fileJson }}
  gcs_key.json: {{ .Files.Get .Values.gcsgateway.fileJson | b64enc }}
  {{- else }}
  gcs_key.json: {{ .Values.gcsgateway.gcsKeyJson | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
